import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { Tree, ProjectConfiguration } from '@nx/devkit';
import generator from './generator.js';
import * as devkit from '@nx/devkit';
import * as astroUtils from '../../utils/astro.js';

vi.mock('@nx/devkit', async () => {
  const actual = await vi.importActual<typeof devkit>('@nx/devkit');
  return {
    ...actual,
    readProjectConfiguration: vi.fn(),
    joinPathFragments: actual.joinPathFragments,
    formatFiles: vi.fn(),
  };
});

vi.mock('../../utils/astro.js', () => ({
  parseAstroConfigDirs: vi.fn(),
}));

describe('page generator', () => {
  let tree: Tree;
  const mockReadProjectConfiguration = vi.mocked(
    devkit.readProjectConfiguration,
  );
  const mockFormatFiles = vi.mocked(devkit.formatFiles);
  const mockParseAstroConfigDirs = vi.mocked(astroUtils.parseAstroConfigDirs);

  const writeSpy = vi.fn<[string, string], void>();

  beforeEach(() => {
    writeSpy.mockReset();
    tree = {
      root: '/workspace',
      exists: vi
        .fn<[string], boolean>()
        .mockReturnValue(false) as unknown as Tree['exists'],
      write: writeSpy as unknown as Tree['write'],
      read: vi.fn<
        [string, string?],
        string | null
      >() as unknown as Tree['read'],
    } as unknown as Tree;

    mockReadProjectConfiguration.mockReturnValue({
      root: 'apps/site',
      name: 'site',
    } as unknown as ProjectConfiguration);

    mockParseAstroConfigDirs.mockReturnValue({
      srcDir: 'src',
      pagesDir: 'src/pages',
      contentDir: 'src/content',
    });
  });

  describe('static pages', () => {
    it('creates a static page file at src/pages/<name>.astro', async () => {
      await generator(tree, { project: 'site', name: 'Home', type: 'static' });

      const call = writeSpy.mock.calls[0];
      const path = call[0].replace(/\\/g, '/');
      expect(path).toContain('apps/site/src/pages/home.astro');
      expect(mockFormatFiles).toHaveBeenCalled();

      const content = call[1];
      expect(content).toContain('---');
      expect(content).toContain(
        '// Generated by @forastro/nx-astro-plugin:page (static)',
      );
      expect(content).toContain('<h1>{title}</h1>');
    });

    it('defaults to static type when not specified', async () => {
      await generator(tree, { project: 'site', name: 'About' });

      const call = writeSpy.mock.calls[0];
      const content = call[1];
      expect(content).toContain(
        '// Generated by @forastro/nx-astro-plugin:page (static)',
      );
    });

    it('supports directory option under src/pages', async () => {
      await generator(tree, {
        project: 'site',
        name: 'About Us',
        directory: 'company',
      });

      const call = writeSpy.mock.calls[0];
      const path = call[0].replace(/\\/g, '/');
      expect(path).toContain('apps/site/src/pages/company/about-us.astro');
    });

    it('uses custom srcDir from astro config', async () => {
      mockParseAstroConfigDirs.mockReturnValue({
        srcDir: 'app',
        pagesDir: 'app/pages',
        contentDir: 'app/content',
      });

      await generator(tree, { project: 'site', name: 'Home' });

      const call = writeSpy.mock.calls[0];
      const path = call[0].replace(/\\/g, '/');
      expect(path).toContain('apps/site/app/pages/home.astro');
    });
  });

  describe('layout support', () => {
    it('generates static page with layout import', async () => {
      await generator(tree, {
        project: 'site',
        name: 'About',
        type: 'static',
        layout: 'BaseLayout',
      });

      const content = writeSpy.mock.calls[0][1];
      expect(content).toContain(
        "import BaseLayout from '../layouts/BaseLayout.astro'",
      );
      expect(content).toContain('<BaseLayout');
      expect(content).toContain('title={title}');
      expect(content).toContain('description={description}');
      expect(content).toContain('</BaseLayout>');
    });

    it('generates dynamic page with layout import', async () => {
      await generator(tree, {
        project: 'site',
        name: 'slug',
        type: 'dynamic',
        layout: 'BlogLayout',
      });

      const content = writeSpy.mock.calls[0][1];
      expect(content).toContain(
        "import BlogLayout from '../layouts/BlogLayout.astro'",
      );
      expect(content).toContain('<BlogLayout');
      expect(content).toContain('title={entry.data.title}');
      expect(content).toContain('description={entry.data.description}');
      expect(content).toContain('</BlogLayout>');
    });

    it('generates static page without layout when not specified', async () => {
      await generator(tree, { project: 'site', name: 'Contact' });

      const content = writeSpy.mock.calls[0][1];
      expect(content).not.toContain('import');
      expect(content).not.toContain('Layout>');
      expect(content).toContain('<div>');
      expect(content).toContain('<h1>{title}</h1>');
    });

    it('generates dynamic page without layout when not specified', async () => {
      await generator(tree, {
        project: 'site',
        name: 'slug',
        type: 'dynamic',
      });

      const content = writeSpy.mock.calls[0][1];
      expect(content).not.toContain('Layout');
      expect(content).toContain('<article>');
      expect(content).toContain('<h1>{entry.data.title}</h1>');
    });
  });

  describe('page content', () => {
    it('includes title and description for static pages', async () => {
      await generator(tree, { project: 'site', name: 'Services' });

      const content = writeSpy.mock.calls[0][1];
      expect(content).toContain('const title = "Services"');
      expect(content).toContain('const description = "Services page description"');
    });

    it('renders content with Content component for dynamic pages', async () => {
      await generator(tree, {
        project: 'site',
        name: 'post',
        type: 'dynamic',
      });

      const content = writeSpy.mock.calls[0][1];
      expect(content).toContain('const { Content } = await entry.render()');
      expect(content).toContain('<Content />');
    });

    it('includes proper article structure for dynamic pages', async () => {
      await generator(tree, {
        project: 'site',
        name: 'blog',
        type: 'dynamic',
      });

      const content = writeSpy.mock.calls[0][1];
      expect(content).toContain('<article>');
      expect(content).toContain('<header>');
      expect(content).toContain('entry.data.title');
      expect(content).toContain('entry.data.description');
      expect(content).toContain('</article>');
    });
  });

  describe('dynamic pages', () => {
    it('creates a dynamic page with getStaticPaths', async () => {
      await generator(tree, { project: 'site', name: 'slug', type: 'dynamic' });

      const call = writeSpy.mock.calls[0];
      const path = call[0].replace(/\\/g, '/');
      const content = call[1];

      expect(path).toContain('apps/site/src/pages/[slug].astro');
      expect(content).toContain(
        '// Generated by @forastro/nx-astro-plugin:page (dynamic)',
      );
      expect(content).toContain(
        "import { getCollection } from 'astro:content'",
      );
      expect(content).toContain('export async function getStaticPaths()');
      expect(content).toContain('params: { slug: entry.slug }');
      expect(content).toContain('const { entry } = Astro.props');
    });

    it('wraps page name in brackets for dynamic pages', async () => {
      await generator(tree, {
        project: 'site',
        name: 'post-id',
        type: 'dynamic',
      });

      const call = writeSpy.mock.calls[0];
      const path = call[0].replace(/\\/g, '/');
      expect(path).toContain('[post-id].astro');
    });

    it('supports directory option for dynamic pages', async () => {
      await generator(tree, {
        project: 'site',
        name: 'id',
        type: 'dynamic',
        directory: 'blog',
      });

      const call = writeSpy.mock.calls[0];
      const path = call[0].replace(/\\/g, '/');
      expect(path).toContain('apps/site/src/pages/blog/[id].astro');
    });

    it('uses custom srcDir for dynamic pages', async () => {
      mockParseAstroConfigDirs.mockReturnValue({
        srcDir: 'app',
        pagesDir: 'app/pages',
        contentDir: 'app/content',
      });

      await generator(tree, { project: 'site', name: 'slug', type: 'dynamic' });

      const call = writeSpy.mock.calls[0];
      const path = call[0].replace(/\\/g, '/');
      expect(path).toContain('apps/site/app/pages/[slug].astro');
    });
  });
});
