import type { Tree } from '@nx/devkit';
import {
  readProjectConfiguration,
  formatFiles,
  joinPathFragments,
} from '@nx/devkit';
import { join } from 'node:path';
import { parseAstroConfigDirs } from '../../utils/astro.js';
import { toKebab } from '../../utils/naming.js';

interface Schema {
  project: string;
  name: string;
  directory?: string;
  type?: 'static' | 'dynamic';
  layout?: string;
}

function generateStaticPage(name: string, layout?: string): string {
  const layoutImport = layout
    ? `import ${layout} from '../layouts/${layout}.astro';\n`
    : '';
  const layoutWrapper = layout
    ? `<${layout} title={title} description={description}>\n  `
    : '';
  const layoutClose = layout ? `\n</${layout}>` : '';
  const indent = layout ? '  ' : '';

  return `---
// Generated by @forastro/nx-astro-plugin:page (static)
${layoutImport}const title = "${name}";
const description = "${name} page description";
---

${layoutWrapper}${indent}<div>
${indent}  <h1>{title}</h1>
${indent}  <!-- TODO: Add your page content here -->
${indent}</div>${layoutClose}
`;
}

function generateDynamicPage(
  name: string,
  layout?: string,
): string {
  const paramName = toKebab(name);
  const layoutImport = layout
    ? `import ${layout} from '../layouts/${layout}.astro';\n`
    : '';
  const layoutWrapper = layout
    ? `<${layout}\n  title={entry.data.title}\n  description={entry.data.description}\n>\n  `
    : '';
  const layoutClose = layout ? `\n</${layout}>` : '';
  const indent = layout ? '  ' : '';

  return `---
// Generated by @forastro/nx-astro-plugin:page (dynamic)
${layoutImport}import { getCollection } from 'astro:content';

export async function getStaticPaths() {
  // TODO: Change 'posts' to your target collection name
  const entries = await getCollection('posts');
  return entries.map(entry => ({
    params: { ${paramName}: entry.slug },
    props: { entry },
  }));
}

const { entry } = Astro.props;
const { Content } = await entry.render();
---

${layoutWrapper}${indent}<article>
${indent}  <header>
${indent}    <h1>{entry.data.title}</h1>
${indent}    {entry.data.description && (
${indent}      <p class="description">{entry.data.description}</p>
${indent}    )}
${indent}  </header>
${indent}  <Content />
${indent}</article>${layoutClose}
`;
}

/**
 * Generate an Astro page (static or dynamic).
 *
 * Creates a new page in the Astro project's pages directory. Supports both static
 * pages and dynamic pages with getStaticPaths for content collections.
 *
 * @param tree - Nx virtual file system tree
 * @param options - Page generation options
 * @param options.project - Name of the Nx project
 * @param options.name - Name of the page (will be converted to kebab-case)
 * @param options.directory - Optional subdirectory under src/pages
 * @param options.type - Page type: 'static' (default) or 'dynamic'
 * @param options.layout - Optional layout component name to wrap the page content
 *
 * @example
 * // Generate a static about page
 * await generator(tree, {
 *   project: 'my-site',
 *   name: 'About Us',
 *   type: 'static',
 *   layout: 'BaseLayout'
 * });
 * // Creates: src/pages/about-us.astro with BaseLayout wrapper
 *
 * @example
 * // Generate a dynamic page with getStaticPaths
 * await generator(tree, {
 *   project: 'my-site',
 *   name: 'slug',
 *   type: 'dynamic',
 *   layout: 'BlogLayout'
 * });
 * // Creates: src/pages/[slug].astro with getStaticPaths() and BlogLayout
 */
export default async function generator(tree: Tree, options: Schema) {
  const proj = readProjectConfiguration(tree, options.project);
  const pageType = options.type || 'static';

  // Parse Astro config to get pagesDir
  const { pagesDir } = parseAstroConfigDirs(proj.root);

  let pageName = toKebab(options.name);

  // For dynamic pages, ensure brackets around param name
  if (pageType === 'dynamic' && !pageName.includes('[')) {
    pageName = `[${pageName}]`;
  }

  const baseDir = options.directory
    ? options.directory.replace(/\\/g, '/')
    : '';
  const targetDir = joinPathFragments(proj.root, pagesDir, baseDir);
  const filePath = join(targetDir, `${pageName}.astro`);

  if (!tree.exists(filePath)) {
    const contents =
      pageType === 'dynamic'
        ? generateDynamicPage(options.name, options.layout)
        : generateStaticPage(options.name, options.layout);
    tree.write(filePath, contents);
  }

  await formatFiles(tree);
}
