/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Border: typeof import('./src/components/Border.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Center: typeof import('./src/components/Center.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    IMdiCaretDown: typeof import('~icons/mdi/caret-down')['default']
    IMdiHamburger: typeof import('~icons/mdi/hamburger')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    IMdiSun: typeof import('~icons/mdi/sun')['default']
    IMdiSunny: typeof import('~icons/mdi/sunny')['default']
    IRiMoonFill: typeof import('~icons/ri/moon-fill')['default']
    IRiSun: typeof import('~icons/ri/sun')['default']
    IRiSunFill: typeof import('~icons/ri/sun-fill')['default']
    LightDarkSwitch: typeof import('./src/components/LightDarkSwitch.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    SpacedBox: typeof import('./src/components/SpacedBox.vue')['default']
  }
}
