import type { Tree } from '@nx/devkit';
import { readProjectConfiguration, formatFiles, joinPathFragments } from '@nx/devkit';
import { join } from 'node:path';

interface Schema {
  project: string;
}

export default async function generator(tree: Tree, options: Schema) {
  const proj = readProjectConfiguration(tree, options.project);
  const docsDir = joinPathFragments(proj.root, 'src', 'content', 'docs');

  // Minimal skeleton only — full implementation can expand later
  const indexPath = join(docsDir, 'index.mdx');
  if (!tree.exists(indexPath)) {
    const contents = `---\ntitle: Getting Started\n---\n\n# Starlight Docs\n\nThis is a placeholder generated by @forastro/nx-astro-plugin:starlight-docs.\n`;
    tree.write(indexPath, contents);
  }

  await formatFiles(tree);
}