import type { Tree } from '@nx/devkit';
import { readProjectConfiguration, formatFiles, joinPathFragments } from '@nx/devkit';
import { join } from 'node:path';

interface Schema {
  project: string;
  name: string;
  directory?: string;
}

const toPascal = (s: string) => s
  .replace(/[^a-zA-Z0-9]+/g, ' ')
  .split(' ')
  .filter((w): w is string => Boolean(w))
  .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
  .join('');

export default async function generator(tree: Tree, options: Schema) {
  const proj = readProjectConfiguration(tree, options.project);
  const compName = toPascal(options.name);
  const baseDir = options.directory ? options.directory.replace(/\\/g, '/') : '';
  const targetDir = joinPathFragments(proj.root, 'src', 'components', baseDir);
  const filePath = join(targetDir, `${compName}.astro`);

  if (!tree.exists(filePath)) {
    const contents = `---\n// Generated by @forastro/nx-astro-plugin:component\nexport interface Props { title?: string }\nconst { title = '${compName}' } = Astro.props;\n---\n\n<div>{title}</div>\n`;
    tree.write(filePath, contents);
  }

  await formatFiles(tree);
}