name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  # Test and Build Job
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm nx affected -t test --parallel

      - name: Lint code
        run: pnpm nx affected -t lint --parallel

      - name: Astro check
        run: pnpm nx affected -t check --parallel

      - name: Build packages
        run: pnpm nx affected -t build --parallel

  # Release Job (only on main branch)
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true))
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build packages
        run: pnpm nx run-many --target=build --projects='tag:nx:lib:ongoing' --parallel

      - name: Release packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Version packages based on commits
          pnpm nx release version --yes --verbose
          
          # Generate changelogs
          pnpm nx release changelog --yes --verbose
          
          # Publish to npm
          pnpm nx release publish --yes --verbose

  # Dry Run Job (for develop branch and PRs)
  release-dry-run:
    name: Release Dry Run
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/develop' || (github.event_name == 'pull_request' && github.base_ref == 'main')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm nx run-many --target=build --projects='tag:nx:lib:ongoing' --parallel

      - name: Release dry run
        run: |
          echo "🔍 Running release dry run to preview changes..."
          pnpm nx release changelog --dry-run --verbose
          pnpm nx release version --dry-run --verbose

      - name: Comment PR with release preview
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            
            try {
              const changelog = execSync('pnpm nx release changelog --dry-run', { encoding: 'utf8' });
              const version = execSync('pnpm nx release version --dry-run', { encoding: 'utf8' });
              
              const body = `## 📦 Release Preview
              
              This PR will trigger the following releases when merged to main:
              
              ### Version Changes
              \`\`\`
              ${version}
              \`\`\`
              
              ### Changelog Preview
              \`\`\`
              ${changelog}
              \`\`\`
              
              *This is an automated preview. Actual release will happen after merge.*`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            } catch (error) {
              console.log('No release changes detected or error running dry run:', error.message);
            }
